// PRCreationModal.jsx
// Modal to create a GitHub PR with security fixes

import { useState, useEffect, useMemo } from 'react';
import {
  X, GitBranch, Send, Loader2, AlertCircle, CheckCircle2, ExternalLink, LogIn,
  Shield, ShieldCheck, ShieldAlert, Eye, Lock, Globe,
} from 'lucide-react';

const API_URL = 'https://remidix-backend.onrender.com';

/** Resolve owner + repo from a project object. Returns { owner, repo } or null. */
function resolveOwnerRepo(project) {
  let owner = project?.githubOwner || project?.github_owner || null;
  let repo  = project?.githubRepo  || project?.github_repo  || null;

  if (!owner || !repo) {
    const rawUrl =
      project?.repos?.[0]?.url ||
      project?.githubUrl ||
      project?.github_url ||
      project?.repo_url ||
      project?.url ||
      '';
    if (rawUrl) {
      const m = rawUrl.match(/github\.com[/:]([^/]+)\/([^/.]+)/i);
      if (m) { owner = m[1]; repo = m[2]; }
    }
  }

  if (repo && repo.endsWith('.git')) {
    repo = repo.slice(0, -4);
  }

  return owner && repo ? { owner, repo } : null;
}

export default function PRCreationModal({ isOpen, onClose, project, findings, filesOriginal, filesCorrected }) {
  const [step, setStep] = useState('checking'); // 'checking' | 'confirm' | 'creating' | 'done' | 'error'
  const [branchName, setBranchName] = useState('');
  const [prTitle, setPrTitle] = useState('');
  const [prBody, setPrBody] = useState('');
  const [selectedFiles, setSelectedFiles] = useState(new Set());
  const [error, setError] = useState(null);
  const [prResult, setPrResult] = useState(null);
  const [loading, setLoading] = useState(false);
  const [authUserId, setAuthUserId] = useState(null);
  const [repoInfo, setRepoInfo] = useState(null);
  const [verificationResult, setVerificationResult] = useState(null);
  const [progress, setProgress] = useState({ stage: '', message: '' });

  // Identify files that actually contain modifications/fixes
  const allFiles = useMemo(() => {
    const correctedKeys = Object.keys(filesCorrected || {});
    if (correctedKeys.length === 0) {
      return Object.keys(filesOriginal || {});
    }
    const modifiedOnly = correctedKeys.filter((f) => {
      if (!filesOriginal || !(f in filesOriginal)) return true;
      return filesCorrected[f] !== filesOriginal[f];
    });
    return modifiedOnly.length > 0 ? modifiedOnly : correctedKeys;
  }, [filesCorrected, filesOriginal]);

  // Check session and repo info on open
  useEffect(() => {
    if (!isOpen) return;

    const ownerRepo = resolveOwnerRepo(project);
    if (!ownerRepo) {
      setStep('error');
      setError('Could not determine GitHub repository. Make sure the project has a valid GitHub URL.');
      return;
    }

    // Reset state
    setStep('checking');
    setError(null);
    setPrResult(null);
    setLoading(false);
    setVerificationResult(null);
    setProgress({ stage: 'auth', message: 'Checking authentication...' });
    setBranchName(`securecode/fix-${Date.now().toString(36)}`);
    setPrTitle(`chore(security): fix vulnerabilities in ${project?.name || ownerRepo.repo}`);
    setPrBody('Automated security remediation generated by SecureCode AI.');
    setSelectedFiles(new Set(allFiles));

    // Check session
    fetch(`${API_URL}/auth/github/session`, { credentials: 'include' })
      .then(r => r.ok ? r.json() : null)
      .then(data => {
        if (data?.authenticated && data.user) {
          setAuthUserId(String(data.user.id));
          setProgress({ stage: 'repo', message: 'Checking repository access...' });

          // Check repo info
          return fetch(`${API_URL}/github/repo-info?owner=${ownerRepo.owner}&repo=${ownerRepo.repo}`, {
            credentials: 'include',
            headers: { 'x-user-id': String(data.user.id) },
          });
        } else {
          setAuthUserId(null);
          setStep('error');
          setError('Not connected to GitHub. Please log in with GitHub first.');
          return null;
        }
      })
      .then(r => r ? r.json() : null)
      .then(info => {
        if (info) {
          setRepoInfo(info);
          if (!info.accessible) {
            setStep('error');
            setError(info.error || 'Cannot access repository.');
          } else {
            setProgress({ stage: 'verify', message: 'Verifying corrected files...' });

            // Verify files
            const filesToVerify = Array.from(selectedFiles).map(fileName => ({
              path: fileName,
              content: (filesCorrected || {})[fileName] || (filesOriginal || {})[fileName] || '',
              originalContent: (filesOriginal || {})[fileName] || '',
            })).filter(f => f.content && f.content.length > 0);

            return fetch(`${API_URL}/github/verify-fix`, {
              method: 'POST',
              headers: {
                'Content-Type': 'application/json',
                'x-user-id': authUserId || '',
              },
              credentials: 'include',
              body: JSON.stringify({
                owner: ownerRepo.owner,
                repo: ownerRepo.repo,
                files: filesToVerify,
                findings: findings || [],
              }),
            });
          }
        }
        return null;
      })
      .then(r => r ? r.json() : null)
      .then(verification => {
        if (verification) {
          setVerificationResult(verification);
          setStep('confirm');
        }
      })
      .catch(err => {
        console.error('PR modal init error:', err);
        setStep('error');
        setError('Failed to initialize PR creation: ' + err.message);
      });
  }, [isOpen, project, allFiles]);

  if (!isOpen) return null;

  const ownerRepo = resolveOwnerRepo(project);
  const isAuthenticated = !!authUserId;
  const fileCount = selectedFiles.size;
  const issueCount = findings?.length || 0;

  const handleFileToggle = (fileName) => {
    const next = new Set(selectedFiles);
    if (next.has(fileName)) next.delete(fileName);
    else next.add(fileName);
    setSelectedFiles(next);
  };

  const handleCreatePR = async () => {
    setLoading(true);
    setError(null);
    setStep('creating');

    try {
      if (!ownerRepo) throw new Error('Could not determine GitHub owner/repo.');
      if (!isAuthenticated) throw new Error('Not connected to GitHub.');

      const { owner, repo } = ownerRepo;

      const files = Array.from(selectedFiles).map((fileName) => ({
        path: fileName,
        content: (filesCorrected || {})[fileName] || (filesOriginal || {})[fileName] || '',
      })).filter((f) => f.content && f.content.length > 0);

      if (files.length === 0) throw new Error('No files with content to submit.');

      const baseBranch = repoInfo?.defaultBranch || project?.repos?.[0]?.branch || 'main';

      // Stage: Creating branch
      setProgress({ stage: 'branch', message: 'Creating branch...' });

      const response = await fetch(`${API_URL}/github/create-pr`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'x-user-id': authUserId,
        },
        credentials: 'include',
        body: JSON.stringify({
          owner,
          repo,
          baseBranch,
          branchName: branchName.trim(),
          files,
          title: prTitle.trim(),
          body: prBody.trim(),
          findingsSummary: Array.isArray(findings) ? findings.slice(0, 50) : [],
        }),
      });

      let resData;
      const resText = await response.text();
      try {
        resData = JSON.parse(resText);
      } catch {
        throw new Error(`Server returned non-JSON response (HTTP ${response.status}): ${resText.slice(0, 200)}`);
      }

      if (response.status === 401) {
        throw new Error('GitHub authentication required. Please connect your GitHub account in Settings.');
      }

      if (!response.ok) {
        const msg = resData?.details || resData?.error || resData?.message || `HTTP ${response.status}`;
        throw new Error(msg);
      }

      const pr = resData.pr || resData;
      setPrResult(pr);
      setStep('done');
    } catch (err) {
      console.error('PR creation failed:', err);
      setError(err.message || 'Failed to create pull request');
      setStep('error');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div style={{
      position: 'fixed', top: 0, left: 0, right: 0, bottom: 0,
      background: 'rgba(0,0,0,0.75)', display: 'flex', alignItems: 'center', justifyContent: 'center',
      zIndex: 1000, backdropFilter: 'blur(4px)',
    }}>
      <div style={{
        background: 'var(--bg)', borderRadius: '12px', boxShadow: '0 24px 64px rgba(0,0,0,0.5)',
        width: '90%', maxWidth: '620px', maxHeight: '85vh', overflow: 'auto',
        border: '1px solid rgba(255,255,255,0.1)',
      }}>
        {/* Header */}
        <div style={{
          padding: '16px 20px', borderBottom: '1px solid rgba(255,255,255,0.08)',
          display: 'flex', alignItems: 'center', justifyContent: 'space-between',
          position: 'sticky', top: 0, background: 'var(--bg)', zIndex: 1,
        }}>
          <h3 style={{ margin: 0, fontSize: '15px', fontWeight: 600, display: 'flex', alignItems: 'center', gap: '8px' }}>
            <GitBranch size={16} style={{ color: '#a78bfa' }} />
            Create Security Fix Pull Request
          </h3>
          <button onClick={onClose} style={{
            background: 'none', border: 'none', color: '#94a3b8', cursor: 'pointer',
            fontSize: '18px', padding: '4px', display: 'flex', alignItems: 'center',
          }}>
            <X size={18} />
          </button>
        </div>

        <div style={{ padding: '20px' }}>

          {/* STEP: Checking */}
          {step === 'checking' && (
            <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', gap: '16px', padding: '40px 20px' }}>
              <Loader2 size={40} className="spin" style={{ color: '#a78bfa' }} />
              <h4 style={{ margin: 0, fontSize: '14px', fontWeight: 600, color: '#cbd5e1' }}>
                {progress.message || 'Checking repository...'}
              </h4>
              <p style={{ margin: 0, fontSize: '12px', color: '#94a3b8', textAlign: 'center' }}>
                Verifying authentication and repository access.
              </p>
            </div>
          )}

          {/* STEP: Error */}
          {step === 'error' && (
            <div style={{ display: 'flex', flexDirection: 'column', gap: '16px' }}>
              <div style={{
                background: 'rgba(255,107,107,0.1)', border: '1px solid rgba(255,107,107,0.3)',
                borderRadius: '8px', padding: '16px', display: 'flex', gap: '12px',
              }}>
                <AlertCircle size={20} style={{ color: '#ff6b6b', flexShrink: 0 }} />
                <div>
                  <h4 style={{ margin: '0 0 4px', fontSize: '14px', fontWeight: 600, color: '#ff6b6b' }}>
                    Cannot Create Pull Request
                  </h4>
                  <p style={{ margin: 0, fontSize: '12px', color: '#94a3b8', lineHeight: 1.5 }}>
                    {error || 'An error occurred while checking repository access.'}
                  </p>
                </div>
              </div>

              {!isAuthenticated && (
                <div style={{
                  background: 'rgba(245,185,66,0.12)', border: '1px solid rgba(245,185,66,0.35)',
                  borderRadius: '8px', padding: '12px 14px', fontSize: '12px',
                  display: 'flex', alignItems: 'center', gap: '10px',
                }}>
                  <LogIn size={15} style={{ color: '#f5b942' }} />
                  <button
                    onClick={() => window.location.href = 'http://localhost:4000/auth/github/login'}
                    style={{
                      display: 'inline-flex', alignItems: 'center', gap: '4px',
                      padding: '4px 10px', borderRadius: '4px', border: '1px solid rgba(245,185,66,0.5)',
                      background: 'rgba(245,185,66,0.15)', color: '#f5b942', fontSize: '11px',
                      fontWeight: 600, cursor: 'pointer',
                    }}
                  >
                    <LogIn size={11} /> Login to GitHub
                  </button>
                </div>
              )}

              <button onClick={onClose} style={{
                padding: '10px', borderRadius: '8px', border: '1px solid rgba(255,255,255,0.2)',
                background: 'transparent', color: '#cbd5e1', fontWeight: 600, cursor: 'pointer', fontSize: '13px',
              }}>
                Close
              </button>
            </div>
          )}

          {/* STEP: Confirm */}
          {step === 'confirm' && (
            <div style={{ display: 'flex', flexDirection: 'column', gap: '16px' }}>
              <h4 style={{ margin: 0, fontSize: '14px', fontWeight: 600, color: '#cbd5e1' }}>
                Create Security Fix Pull Request?
              </h4>

              {/* Repository Info */}
              {repoInfo && (
                <div style={{
                  background: 'rgba(169,140,240,0.08)', border: '1px solid rgba(169,140,240,0.2)',
                  borderRadius: '8px', padding: '14px', fontSize: '13px',
                }}>
                  <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: '8px' }}>
                    <span style={{ color: '#94a3b8' }}>Repository</span>
                    <span style={{ fontWeight: 600, fontFamily: 'monospace', fontSize: '12px' }}>
                      {repoInfo.owner}/{repoInfo.repo}
                    </span>
                  </div>
                  <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: '8px' }}>
                    <span style={{ color: '#94a3b8' }}>Visibility</span>
                    <span style={{ display: 'flex', alignItems: 'center', gap: '4px', fontWeight: 600 }}>
                      {repoInfo.visibility === 'private' ? (
                        <><Lock size={12} /> Private</>
                      ) : (
                        <><Globe size={12} /> Public</>
                      )}
                    </span>
                  </div>
                  <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: '8px' }}>
                    <span style={{ color: '#94a3b8' }}>Default Branch</span>
                    <span style={{ fontWeight: 600, fontFamily: 'monospace', fontSize: '12px' }}>
                      {repoInfo.defaultBranch}
                    </span>
                  </div>
                  <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: '8px' }}>
                    <span style={{ color: '#94a3b8' }}>Your Access</span>
                    <span style={{ display: 'flex', alignItems: 'center', gap: '4px', fontWeight: 600 }}>
                      {repoInfo.hasWriteAccess ? (
                        <><ShieldCheck size={12} style={{ color: '#4fd08a' }} /> Write Access</>
                      ) : (
                        <><ShieldAlert size={12} style={{ color: '#f5b942' }} /> Read Only (Fork Required)</>
                      )}
                    </span>
                  </div>
                  <div style={{ display: 'flex', justifyContent: 'space-between' }}>
                    <span style={{ color: '#94a3b8' }}>PR Method</span>
                    <span style={{ fontWeight: 600, fontSize: '12px' }}>
                      {repoInfo.hasWriteAccess ? 'Direct Branch' : 'Fork & PR'}
                    </span>
                  </div>
                </div>
              )}

              {/* Verification Result */}
              {verificationResult && (
                <div style={{
                  background: verificationResult.verified ? 'rgba(79,208,138,0.08)' : 'rgba(245,185,66,0.08)',
                  border: `1px solid ${verificationResult.verified ? 'rgba(79,208,138,0.3)' : 'rgba(245,185,66,0.3)'}`,
                  borderRadius: '8px', padding: '14px', fontSize: '13px',
                }}>
                  <div style={{ display: 'flex', alignItems: 'center', gap: '8px', marginBottom: '8px' }}>
                    {verificationResult.verified ? (
                      <ShieldCheck size={16} style={{ color: '#4fd08a' }} />
                    ) : (
                      <ShieldAlert size={16} style={{ color: '#f5b942' }} />
                    )}
                    <span style={{ fontWeight: 600, color: verificationResult.verified ? '#4fd08a' : '#f5b942' }}>
                      {verificationResult.verified ? 'Fix Verified' : 'Verification Issues'}
                    </span>
                  </div>
                  <p style={{ margin: 0, fontSize: '12px', color: '#94a3b8' }}>
                    {verificationResult.message}
                  </p>
                </div>
              )}

              {/* Files to include */}
              <div>
                <h4 style={{ margin: '0 0 8px', fontSize: '13px', fontWeight: 600, color: '#94a3b8' }}>
                  Corrected Files ({fileCount})
                </h4>
                <div style={{
                  background: 'rgba(0,0,0,0.2)', borderRadius: '8px',
                  maxHeight: '150px', overflow: 'auto', border: '1px solid rgba(255,255,255,0.08)',
                }}>
                  {allFiles.map((fileName) => (
                    <label key={fileName} style={{
                      display: 'flex', alignItems: 'center', gap: '8px', padding: '8px 12px',
                      borderBottom: '1px solid rgba(255,255,255,0.04)', cursor: 'pointer',
                    }}>
                      <input
                        type="checkbox" checked={selectedFiles.has(fileName)}
                        onChange={() => handleFileToggle(fileName)}
                        style={{ cursor: 'pointer' }}
                      />
                      <span style={{ fontSize: '12px', color: '#cbd5e1', fontFamily: 'monospace' }}>{fileName}</span>
                    </label>
                  ))}
                </div>
              </div>

              {/* Vulnerabilities */}
              {issueCount > 0 && (
                <div style={{ fontSize: '12px', color: '#94a3b8' }}>
                  <span style={{ fontWeight: 600, color: '#ff6b6b' }}>{issueCount}</span> vulnerabilities will be fixed
                </div>
              )}

              {/* Branch name */}
              <div>
                <label style={{ display: 'block', fontSize: '12px', fontWeight: 600, color: '#94a3b8', marginBottom: '6px' }}>
                  Branch Name
                </label>
                <input
                  type="text" value={branchName} onChange={(e) => setBranchName(e.target.value)}
                  style={{
                    width: '100%', padding: '8px 12px', borderRadius: '6px',
                    background: 'rgba(0,0,0,0.2)', border: '1px solid rgba(255,255,255,0.1)',
                    color: '#cbd5e1', fontSize: '13px', fontFamily: 'monospace', boxSizing: 'border-box',
                  }}
                />
              </div>

              <div style={{ display: 'flex', gap: '8px' }}>
                <button
                  onClick={handleCreatePR}
                  disabled={loading || !branchName.trim() || fileCount === 0}
                  style={{
                    flex: 1, padding: '10px', borderRadius: '8px', border: 'none',
                    background: loading || !branchName.trim() || fileCount === 0 ? 'rgba(79,208,138,0.3)' : '#4fd08a',
                    color: '#000', fontWeight: 600,
                    cursor: loading || !branchName.trim() || fileCount === 0 ? 'not-allowed' : 'pointer',
                    fontSize: '13px', display: 'flex', alignItems: 'center', justifyContent: 'center', gap: '6px',
                  }}
                >
                  <Send size={14} /> Yes, Create Pull Request
                </button>
                <button onClick={onClose} style={{
                  flex: 1, padding: '10px', borderRadius: '8px', border: '1px solid rgba(255,255,255,0.2)',
                  background: 'transparent', color: '#cbd5e1', fontWeight: 600, cursor: 'pointer', fontSize: '13px',
                }}>
                  Cancel
                </button>
              </div>
            </div>
          )}

          {/* STEP: Creating — show real-time progress */}
          {step === 'creating' && (
            <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', gap: '16px', padding: '40px 20px' }}>
              <Loader2 size={40} className="spin" style={{ color: '#a78bfa' }} />
              <h4 style={{ margin: 0, fontSize: '14px', fontWeight: 600, color: '#cbd5e1' }}>
                {progress.message || 'Creating pull request...'}
              </h4>
              <div style={{ display: 'flex', flexDirection: 'column', gap: '8px', fontSize: '12px', color: '#94a3b8' }}>
                <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
                  {progress.stage === 'branch' || progress.stage === 'fixes' || progress.stage === 'commit' || progress.stage === 'pr' ? (
                    <CheckCircle2 size={14} style={{ color: '#4fd08a' }} />
                  ) : (
                    <Loader2 size={14} className="spin" style={{ color: '#a78bfa' }} />
                  )}
                  Creating branch...
                </div>
                <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
                  {progress.stage === 'commit' || progress.stage === 'pr' ? (
                    <CheckCircle2 size={14} style={{ color: '#4fd08a' }} />
                  ) : progress.stage === 'fixes' ? (
                    <Loader2 size={14} className="spin" style={{ color: '#a78bfa' }} />
                  ) : (
                    <div style={{ width: 14, height: 14, borderRadius: '50%', border: '1px solid #94a3b8' }} />
                  )}
                  Applying fixes...
                </div>
                <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
                  {progress.stage === 'pr' ? (
                    <CheckCircle2 size={14} style={{ color: '#4fd08a' }} />
                  ) : progress.stage === 'commit' ? (
                    <Loader2 size={14} className="spin" style={{ color: '#a78bfa' }} />
                  ) : (
                    <div style={{ width: 14, height: 14, borderRadius: '50%', border: '1px solid #94a3b8' }} />
                  )}
                  Creating commit...
                </div>
                <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
                  {progress.stage === 'done' ? (
                    <CheckCircle2 size={14} style={{ color: '#4fd08a' }} />
                  ) : progress.stage === 'pr' ? (
                    <Loader2 size={14} className="spin" style={{ color: '#a78bfa' }} />
                  ) : (
                    <div style={{ width: 14, height: 14, borderRadius: '50%', border: '1px solid #94a3b8' }} />
                  )}
                  Creating Pull Request...
                </div>
              </div>
            </div>
          )}

          {/* STEP: Done — show success with real PR data */}
          {step === 'done' && prResult && (
            <div style={{ display: 'flex', flexDirection: 'column', gap: '16px' }}>
              <div style={{
                background: 'rgba(79,208,138,0.1)', border: '1px solid rgba(79,208,138,0.3)',
                borderRadius: '8px', padding: '16px', display: 'flex', gap: '12px',
              }}>
                <CheckCircle2 size={20} style={{ color: '#4fd08a', flexShrink: 0 }} />
                <div>
                  <h4 style={{ margin: '0 0 4px', fontSize: '14px', fontWeight: 600, color: '#4fd08a' }}>
                    Pull Request Created!
                  </h4>
                  <p style={{ margin: 0, fontSize: '12px', color: '#94a3b8' }}>
                    Your security fixes have been pushed and the PR is now open on GitHub.
                  </p>
                </div>
              </div>

              <div style={{
                background: 'rgba(0,0,0,0.2)', borderRadius: '8px', padding: '14px',
                fontSize: '12px', display: 'flex', flexDirection: 'column', gap: '8px',
              }}>
                {prResult.number && (
                  <div style={{ display: 'flex', justifyContent: 'space-between' }}>
                    <span style={{ color: '#94a3b8' }}>PR Number</span>
                    <span style={{ fontWeight: 600 }}>#{prResult.number}</span>
                  </div>
                )}
                {prResult.title && (
                  <div style={{ display: 'flex', justifyContent: 'space-between', gap: '12px' }}>
                    <span style={{ color: '#94a3b8', flexShrink: 0 }}>Title</span>
                    <span style={{ textAlign: 'right' }}>{prResult.title}</span>
                  </div>
                )}
                {(prResult.sourceBranch || prResult.head?.ref) && (
                  <div style={{ display: 'flex', justifyContent: 'space-between', gap: '12px' }}>
                    <span style={{ color: '#94a3b8', flexShrink: 0 }}>Branch</span>
                    <span style={{ fontFamily: 'monospace', fontSize: '11px' }}>
                      {prResult.sourceBranch || prResult.head?.ref}
                    </span>
                  </div>
                )}
                {prResult.commitSha && (
                  <div style={{ display: 'flex', justifyContent: 'space-between' }}>
                    <span style={{ color: '#94a3b8' }}>Commit</span>
                    <span style={{ fontFamily: 'monospace', fontSize: '11px' }}>
                      {prResult.commitSha.slice(0, 7)}
                    </span>
                  </div>
                )}
                {(prResult.changedFiles != null) && (
                  <div style={{ display: 'flex', justifyContent: 'space-between' }}>
                    <span style={{ color: '#94a3b8' }}>Files Changed</span>
                    <span style={{ fontWeight: 600 }}>{prResult.changedFiles}</span>
                  </div>
                )}
                {prResult.isFork && (
                  <div style={{ display: 'flex', justifyContent: 'space-between' }}>
                    <span style={{ color: '#94a3b8' }}>Method</span>
                    <span style={{ fontWeight: 600, fontSize: '11px' }}>Fork & PR</span>
                  </div>
                )}
              </div>

              <div style={{ display: 'flex', gap: '8px' }}>
                {(prResult.url || prResult.html_url) && (
                  <a
                    href={prResult.url || prResult.html_url}
                    target="_blank" rel="noreferrer"
                    style={{
                      flex: 1, padding: '10px', borderRadius: '8px', border: 'none',
                      background: '#a78bfa', color: '#000', fontWeight: 600, cursor: 'pointer',
                      fontSize: '13px', display: 'flex', alignItems: 'center', justifyContent: 'center', gap: '6px',
                      textDecoration: 'none',
                    }}
                  >
                    <ExternalLink size={14} /> Open Pull Request
                  </a>
                )}
                <button onClick={onClose} style={{
                  flex: 1, padding: '10px', borderRadius: '8px', border: '1px solid rgba(255,255,255,0.2)',
                  background: 'transparent', color: '#cbd5e1', fontWeight: 600, cursor: 'pointer', fontSize: '13px',
                }}>
                  Close
                </button>
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
